services:
  - type: web
    name: navigate-this
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: navigate-this-db
          property: connectionString
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: navigate-this-db
    databaseName: navigate_this
    user: navigate_user

